
data.raw.tile["natural-yumako-soil"].absorptions_per_second = {pollution = 0.00004}
data.raw.tile["natural-jellynut-soil"].absorptions_per_second = {pollution = 0.00004}
data.raw.tile["lowland-brown-blubber"].absorptions_per_second = {pollution = 0.00004}
data.raw.tile["lowland-olive-blubber"].absorptions_per_second = {pollution = 0.00004}
data.raw.tile["lowland-olive-blubber-2"].absorptions_per_second = {pollution = 0.00004}
data.raw.tile["lowland-olive-blubber-3"].absorptions_per_second = {pollution = 0.00004}
data.raw.tile["lowland-pale-green"].absorptions_per_second = {pollution = 0.00004}
data.raw.tile["lowland-cream-cauliflower"].absorptions_per_second = {pollution = 0.00004}
data.raw.tile["lowland-cream-cauliflower-2"].absorptions_per_second = {pollution = 0.00004}
data.raw.tile["lowland-dead-skin"].absorptions_per_second = {pollution = 0.00004}
data.raw.tile["lowland-dead-skin-2"].absorptions_per_second = {pollution = 0.00004}
data.raw.tile["lowland-cream-red"].absorptions_per_second = {pollution = 0.00004}
data.raw.tile["lowland-red-vein"].absorptions_per_second = {pollution = 0.00003}
data.raw.tile["lowland-red-vein-2"].absorptions_per_second = {pollution = 0.00003}
data.raw.tile["lowland-red-vein-3"].absorptions_per_second = {pollution = 0.00003}
data.raw.tile["lowland-red-vein-4"].absorptions_per_second = {pollution = 0.00003}
data.raw.tile["lowland-red-vein-dead"].absorptions_per_second = {pollution = 0.00003}
data.raw.tile["lowland-red-infection"].absorptions_per_second = {pollution = 0.00003}
data.raw.tile["midland-turquoise-bark"].absorptions_per_second = {pollution = 0.00004}
data.raw.tile["midland-turquoise-bark-2"].absorptions_per_second = {pollution = 0.00004}
data.raw.tile["midland-cracked-lichen"].absorptions_per_second = {pollution = 0.00002}
data.raw.tile["midland-cracked-lichen-dull"].absorptions_per_second = {pollution = 0.00002}
data.raw.tile["midland-cracked-lichen-dark"].absorptions_per_second = {pollution = 0.00002}
data.raw.tile["midland-yellow-crust"].absorptions_per_second = {pollution = 0.000025}
data.raw.tile["midland-yellow-crust-2"].absorptions_per_second = {pollution = 0.000025}
data.raw.tile["midland-yellow-crust-3"].absorptions_per_second = {pollution = 0.000025}
data.raw.tile["midland-yellow-crust-4"].absorptions_per_second = {pollution = 0.000025}
data.raw.tile["highland-dark-rock"].absorptions_per_second = {pollution = 0.00002}
data.raw.tile["highland-dark-rock-2"].absorptions_per_second = {pollution = 0.00002}
data.raw.tile["highland-yellow-rock"].absorptions_per_second = {pollution = 0.00002}
data.raw.tile["pit-rock"].absorptions_per_second = {pollution = 0.000015}
